package computer.fuji.al0.models;

public class KeyboardButtonModel {
    public static enum KeyboardButtonId {
        // number
        BUTTON_0, BUTTON_1, BUTTON_2, BUTTON_3, BUTTON_4, BUTTON_5, BUTTON_6, BUTTON_7, BUTTON_8, BUTTON_9,
        // uppercase
        BUTTON_GENERIC,
        BUTTON_Q, BUTTON_W, BUTTON_E, BUTTON_R, BUTTON_T, BUTTON_Y, BUTTON_U, BUTTON_I, BUTTON_O, BUTTON_P,
        BUTTON_A, BUTTON_S, BUTTON_D, BUTTON_F, BUTTON_G, BUTTON_H, BUTTON_J, BUTTON_K, BUTTON_L,
        BUTTON_Z, BUTTON_X, BUTTON_C, BUTTON_V, BUTTON_B, BUTTON_N, BUTTON_M,
        // lowercase
        BUTTON_q, BUTTON_w, BUTTON_e, BUTTON_r, BUTTON_t, BUTTON_y, BUTTON_u, BUTTON_i, BUTTON_o, BUTTON_p,
        BUTTON_a, BUTTON_s, BUTTON_d, BUTTON_f, BUTTON_g, BUTTON_h, BUTTON_j, BUTTON_k, BUTTON_l,
        BUTTON_z, BUTTON_x, BUTTON_c, BUTTON_v, BUTTON_b, BUTTON_n, BUTTON_m,
        // symbols
        BUTTON_SPACE, BUTTON_EXCLAMATION_MARK, BUTTON_DOUBLE_QUOTES, BUTTON_NUMBER, BUTTON_DOLLAR, BUTTON_PER_CENT,
        BUTTON_AMPERSAND, BUTTON_SINGLE_QUOTE, BUTTON_OPEN_PARENTHESIS, BUTTON_CLOSE_PARENTHESIS, BUTTON_ASTERISK,
        BUTTON_PLUS, BUTTON_COMMA, BUTTON_HYPHEN, BUTTON_DOT, BUTTON_SLASH,
        // controls
        BUTTON_DIACRITIC, BUTTON_PASTE, BUTTON_DELETE_WORD, BUTTON_MOVE_CURSOR_LEFT, BUTTON_MOVE_CURSOR_RIGHT, BUTTON_MOVE_CURSOR_LEFT_WORD, BUTTON_MOVE_CURSOR_RIGHT_WORD,
        BUTTON_UPPERCASE, BUTTON_LOWERCASE, BUTTON_DELETE,
        // layout
        BUTTON_NOTHING,
        // numbers
        BUTTON_MINUS, BUTTON_COLON, BUTTON_SEMI_COLON, BUTTON_EURO, BUTTON_AT, BUTTON_SYMBOLS, BUTTON_QUESTION_MARK,
        // symbols
        BUTTON_OPEN_SQUARED, BUTTON_CLOSE_SUARED, BUTTON_OPEN_CURLY, BUTTON_CLOSE_CURLY, BUTTON_HASH, BUTTON_POWER, BUTTON_EQUAL, BUTTON_LOWDASH, BUTTON_BACK_SLASH, BUTTON_BAR, BUTTON_TILDE, BUTTON_LESS_THAN, BUTTON_GREATER_THAN, BUTTON_STERLING, BUTTON_YEN, BUTTON_MIDDLE_DOT
    }

    private final KeyboardButtonId id;
    private final String key;

    public KeyboardButtonModel (KeyboardButtonId id, String key) {
        this.id = id;
        this.key = key;
    }

    public KeyboardButtonId getId() {
        return id;
    }

    public String getKey() {
        return key;
    }
}

